import 'package:ecomapp/models/product.dart';
//step 18

class MyProducts {
  static List<Product> allProducts = [
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 180.00,
      image: 'assets/sneakers_pictures/1.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike Originals',
      price: 120.00,
      image: 'assets/sneakers_pictures/2.jpg',
      category: "Out of Stock",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Addidas New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/3.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: ' New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/4.jpg',
      category: " Loream Ipsum",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'hafj New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/5.jpg',
      category: "afkj Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jacket 1',
      price: 180.00,
      image: 'assets/jacket_pictures/1.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Jacket 2',
      price: 120.00,
      image: 'assets/jacket_pictures/2.jpg',
      category: "Out of Stock",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jacket 3',
      price: 180.00,
      image: 'assets/jacket_pictures/3.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: ' jacket 4',
      price: 180.00,
      image: 'assets/jacket_pictures/4.jpg',
      category: " Loream Ipsum",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
  ];

  static List<Product> sneakersList = [
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 180.00,
      image: 'assets/sneakers_pictures/1.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Nike Originals',
      price: 120.00,
      image: 'assets/sneakers_pictures/2.jpg',
      category: "Out of Stock",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Addidas New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/3.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: ' New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/4.jpg',
      category: " Loream Ipsum",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'hafj New born',
      price: 180.00,
      image: 'assets/sneakers_pictures/5.jpg',
      category: "afkj Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
  ];

  static List<Product> jacketsList = [
    Product(
      id: 1,
      name: 'jacket 1',
      price: 180.00,
      image: 'assets/jacket_pictures/1.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'Jacket 2',
      price: 120.00,
      image: 'assets/jacket_pictures/2.jpg',
      category: "Out of Stock",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: 'jacket 3',
      price: 180.00,
      image: 'assets/jacket_pictures/3.jpg',
      category: "Trending Now",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
    Product(
      id: 1,
      name: ' jacket 4',
      price: 180.00,
      image: 'assets/jacket_pictures/4.jpg',
      category: " Loream Ipsum",
      description: "Clean lines, Versatile and timeless",
      quantity: 1,
    ),
  ];
}

//step 19 - add assets and update pubspec.yaml